---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: simplificator.caddy

  vars:
    caddy_sites:
      - domain: example.com
        routes:
          - path: ''
            reverse_proxy_destination: 192.168.50.2
        redirects:
          - source: ''
            target: /
          - source: '/about-us'
            target: '/about'
            code: 401
        allowlist:
          - 8.8.8.8/32
        additional_forwarding_ports:
          - '8080'
          - '1337'
        additional_template_path: "./templates/additions.j2"
      - domain: test.com
        routes:
          - path: ''
            reverse_proxy_destination: 192.168.50.1
      - domain: mixed.example.com
        routes:
          - path: '/public/*'
            ignore_allowlist: true
            reverse_proxy_destination: 192.168.50.3
          - path: '/protected/*'
            strip_prefix: true
            reverse_proxy_destination: 192.168.50.4
        allowlist:
          - 8.8.8.8/32
